/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.bfur64"
version = "2.0.0"

val jline3Version = "3.30.13"

tasks.processResources {
    val tetrueTerminalVersion = project.version.toString()
    val jline3Version = jline3Version

    inputs.property("tetrueTerminalVersion", tetrueTerminalVersion)
    inputs.property("jline3Version", jline3Version)

    filesMatching("io/github/bfur64/terminal/settings.json.template") {
        expand(
            "tetrueTerminalVersion" to tetrueTerminalVersion,
            "jline3Version" to jline3Version
        )
    }

    rename("(.+)\\.template", "$1")
}

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("application")

    id("com.gradleup.shadow") version "9.3.1"

    id("com.vanniktech.maven.publish") version "0.36.0"
}

shadow {
    addShadowVariantIntoJavaComponent = false
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    // Rendering Pipeline
    implementation("org.jline:jline:$jline3Version")

    // JSON Reader
    implementation("tools.jackson.core:jackson-databind:3.1.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "examples.ExtremeTest"
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(group.toString(), "tetrue-terminal", version.toString())

    pom {
        name.set("menu-manager")
        description.set("A meta library that combines JLine3 and Lanterna for my specific purposes")
        inceptionYear.set("2026")
        url.set("https://github.com/BFUR64/tetrue-terminal")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/license/mit")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("BFUR64")
                name.set("Terrance")
                url.set("https://github.com/BFUR64/")
            }
        }
        scm {
            url.set("https://github.com/BFUR64/tetrue-terminal")
            connection.set("scm:git:https://github.com/BFUR64/tetrue-terminal.git")
            developerConnection.set("scm:git:ssh://git@github.com/BFUR64/tetrue-terminal.git")
        }
    }
}