/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.bfur64"
version = "3.0.0-SNAPSHOT"

val lanternaVersion = project.properties["lanternaVersion"] as String
val jlineVersion = project.properties["jlineVersion"] as String

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("com.vanniktech.maven.publish") version "0.36.0"
    id("com.github.gmazzo.buildconfig") version "6.0.10"
}

buildConfig {
    className("Versions")
    packageName(group.toString())
    useJavaOutput()

    buildConfigField("String", "TETRUE_TERMINAL", "\"${project.version}\"")
    buildConfigField("String", "LANTERNA", "\"${lanternaVersion}\"")
    buildConfigField("String", "JLINE", "\"${jlineVersion}\"")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // Rendering Pipeline
    implementation("com.googlecode.lanterna:lanterna:${lanternaVersion}")
    implementation("org.jline:jline:$jlineVersion")

    // Logger
    implementation("org.apache.logging.log4j:log4j-api:2.26.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(group.toString(), "tetrue-terminal", version.toString())

    pom {
        name.set("menu-manager")
        description.set("A meta library that combines JLine and Lanterna for my specific purposes")
        inceptionYear.set("2026")
        url.set("https://github.com/BFUR64/tetrue-terminal")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/license/mit")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("BFUR64")
                name.set("Terrance")
                url.set("https://github.com/BFUR64/")
            }
        }
        scm {
            url.set("https://github.com/BFUR64/tetrue-terminal")
            connection.set("scm:git:https://github.com/BFUR64/tetrue-terminal.git")
            developerConnection.set("scm:git:ssh://git@github.com/BFUR64/tetrue-terminal.git")
        }
    }
}